//Local Host: 
### All Movies
GET http://localhost:3000/movies

# ONE CONTACT
###Matilda
GET http://localhost:3000/movies/6334a389e784cb4ce76ca99a HTTP/1.1

###The Avengers
GET http://localhost:3000/movies/6334a3e9e784cb4ce76ca99b HTTP/1.1

###Knives Out
GET http://localhost:3000/movies/6334a402e784cb4ce76ca99c HTTP/1.1


###Add New Movie
POST http://localhost:3000/movies  HTTP/1.1
Content-Type: application/json

{
    "title": "The Avengers",
   "genre": "Action",
   "subGenres": "superhero, comedy",
    "rating": "pg-13",
    "content": "violence, language",
    "releaseYear": "2012",
    "purchaseDate": "09/14/2012"
}


###UPDATE CONTACT
PUT http://localhost:3000/movies/6334c4a6c1c98838e6cfe4c5 HTTP/1.1
Content-Type: application/json

{
    
    "title": "The Avengers",
   "genre": "Action",
   "subGenres": "superhero, comedy",
    "rating": "pg-13",
    "content": "violence, language",
    "releaseYear": "2012",
    "purchaseDate": "09/14/2012"
}

###DELETE CONTACT

DELETE http://localhost:3000/movies/6334c4a6c1c98838e6cfe4c5